### ISSUE TITLE
Removing an archived task will switch to the active tab.

### ISSUE THREAD

**Issue by GabMic** [fl2top/laravel-todo#2]
When you are in the archive tab and press the delete button on a completed task, it will, in fact, remove and delete the task, but it constantly takes you to the active tab after each delete action. 
The delete function will call the `fetchTaskList()` method, and there is the problem i think with the setActive.
how can we fix this?
Thanks.

**Comment by mitrallex** [comment]
There is no problem with the setActive method. In the fetchTaskList method we already have all that you want:
````javascript
if (archive === null) {
     var url = 'current_tasks';
     this.setActive('current');
} else {
    var url = 'archived_tasks';
    this.setActive('archive');
}
````
As you can see in the fetchTaskList method we check incoming variable 'archive', and if it is null - fetch current task list, otherwise - archived task list.
So just check _activeItem_ in the deleteTask and/or in the archiveTask methods. And then just pass the parameter to the function (as in the template section, where we fetch task list on tab clicking). 
 
````javascript
if (this.activeItem === 'archive') {
    this.fetchTaskList(1);
 } else {
     this.fetchTaskList();
}
````
Here is the deleteTask method after all:
````javascript
deleteTask(id) {
     axios.post('delete_task/' + id).then(result => {
        if (this.activeItem === 'archive') {
             this.fetchTaskList(1);
         } else {
             this.fetchTaskList();
         }
     }).catch(err => {
         console.log(err);
     });
 },
````

**Comment by GabMic** [comment]
Yes, that solved the problem. You should update the code in the repo also.
And by the way, all the play with the active state of the tabs is not needed. I have made for this a `Tabs` component and a `Tab` component also. It will simplify things a lot, and make it easier to reproduce. I think you should consider using it in this repo. it should work like a charm.  

Here is the `Tabs` component:
```
<template>
    <div>
        <div class="tabs is-centered is-large is-boxed">
            <ul>
                <li v-for="tab in tabs" :class="{ 'is-active': tab.isActive }">
                    <a @click="selectTab(tab)">{{ tab.name }}</a>
                </li>
            </ul>
        </div>
        <div class="tabs-details">
            <slot></slot>
        </div>
    </div>
</template>


<script>
    import Tab from '../components/Tab.vue';
    export default{
        components: {Tab},
        data() {
            return { tabs: [] };
        },
        created() {
            this.tabs = this.$children;
        },
        methods: {
            selectTab(selectedTab) {
                this.tabs.forEach(tab => {
                    tab.isActive = (tab.name == selectedTab.name);
                });
            }
        }
    }
</script>
```


And this is the `Tab` component:
```
<template>
    <div v-show="isActive"><slot></slot></div>
</template>


<script>
    export default{
        props: {
            name: { required: true },
            selected: { default: false }
        },

        data() {
            return {
                isActive: false
            };
        },

        mounted() {
            this.isActive = this.selected;
        }
    }
</script>
```

And you use it like this in your views:
```
<tabs>
    <tab name="some name" :selected="true">
       <h1>put what ever you want in here</h1>
   </tab>
    <tab name="some other name">
       <h1>put what ever you want in here</h1>
      **You can put as many tabs as you want, just give them a name.**
  </tab>
</tabs>
```

**Comment by mitrallex** [comment]
Excellent! Thank you. I will update the code later, but in the specific branch. The master branch must be original (for this article - https://codeburst.io/simple-to-do-application-with-laravel-and-vue-4af28cb007ad).

**Comment by GabMic** [comment]
Great. waiting for the integration of the tabs. It will be approximately 60% faster on a real server then what you have now. @fl2top

**Comment by mitrallex** [comment]
@GabMic, I carefully looked your example with tabs and I understood why these Vue components seemed familiar for me - @JeffreyWay in [this course](https://laracasts.com/series/learn-vue-2-step-by-step/episodes/11) showed these components. Exactly the same.
I thought about adding tabs in this todo application.. and finally decided that in this case it's not necessary. If we add these two components - it will not change anything. There also will be condition to checking what tab is it. It's just will be not one component but three.
So may be later I finally will do it, but now I have another idea about using these tabs components. And I hope that soon I will write article about it on medium.com and create new public repository here. I will notify you about it. 
Thank you for participating. I'm novice in Vue so it's very important for me.
